### ISSUE TITLE
Remote Connection In case of database buffering.

### ISSUE THREAD

**Issue by Gicehajunior** [humolot/cPanel-API-Simple-PHP#2]
Thinking of How it can be made to connect with your database locally. 
Having your system on your local machine, and then having your database hosted on the cpanel.
Well, I'm looking for a way I can connect to it remotely using the cpanel API,  in case internet is available the database hosted is use. well, if no available internet, my local database is used instead.

I can see that this method, $api->checkDataBaseMySQL(), works. That's great.

In addition, question, How can dump data on a specific table can be implemented?

**Comment by humolot** [comment]
Hi Bro, This function is not available around the cPanel API, only the full database dump.

**Comment by Gicehajunior** [comment]
Any logic we can apply in such case on a one's personal project?
