### ISSUE TITLE
$api->createEmail() is not working on some cpanels

### ISSUE THREAD

**Issue by Gicehajunior** [humolot/cPanel-API-Simple-PHP#3]
I hosted an app on a server A.
Went ahead and tried to create emails using the API on the same server.
Found that the createEmail() is not working on this server but working when on localhost.

Again, tried to host the app on another server B,
the function can't create emails on server A, but can create the emails on this server B.

Any walk-around to counter this?

**Comment by John-Henrique** [comment]
Same problem here, createEmail() just return false

**Comment by Gicehajunior** [comment]
Could you please use Ajax for that? It worked for me.

**Comment by John-Henrique** [comment]
> Could you please use Ajax for that? It worked for me.

But ajax or not, the function to execute action in PHP is same... The result will be same.

Why don`t why work some servers and not in others...

**Comment by John-Henrique** [comment]
@humolot can you give us a help?

**Comment by Gicehajunior** [comment]
It woud be nice if you post the log messages you do get?

**Comment by John-Henrique** [comment]
Just receive false

Debuging I can see something a little bit strange...

By default, all requests points to port 2083, but in email route result in 

`[08-Mar-2022 05:44:11 UTC] curl_exec threw error "Failed to connect to doma.in port 2083 after 3 ms: Connection refused" for https://doma.in:2083/execute/Email/add_pop?email=testEmail&password=Dw(7!mER3MFC&quota=0&domain=doma.in&send_welcome_email=1`

Typing this on browser, cPanel request a new session (is correct, in this case) but, looks like createEmail no have access...

**Comment by Gicehajunior** [comment]
Use correct domain or ip address and correct domain login credentials. I'm sure it should work.

**Comment by John-Henrique** [comment]
@Gicehajunior Sorry if I no put real info on my last example, but believe me, I just using correct URL and credentials.
